baseURL = "https://triplenickelpigs.com"
title = "Triple Nickel"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tnp"
enableRobotsTXT = true
description = "Premium Pork, For Your Fork"
copyright = 'Triple Nickel 2023'
paginate = 6



[menu]

  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/pricing/"
    weight = 10
  
  [[menu.main]]
    identifier = "waitlist"
    name = "Wait List"
    url = "/waitlist/"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  #[[menu.footer]]
  #  name = ""
  #  url = ""
  #  pre = ""
  #    weight = 2

