[build]
publish = "public"
command = "npm run build"

    [build.environment]
        HUGO_VERSION = "0.90.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build"

    [context.split1.environment]
    HUGO_VERSION = "0.90.0"
    HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build"

[context.branch-deploy]
command = "npm run build"


[context.next.environment]
HUGO_ENABLEGITINFO = "true"
